#!/bin/bash

# JAVA path
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export PATH=$JAVA_HOME/bin:$PATH

# aws access variables 
aws_access_key_id=ASIAT7ZCEPHYI3FSC7KO
aws_secret_access_key=OArKyg29yfc5o1alxZlHKn/ms98HBlBlROGLvTqm
aws_session_token=IQoJb3JpZ2luX2VjELD//////////wEaCXVzLXdlc3QtMiJHMEUCIHKArN7s/+Z4F3csjBJHmOjxAk3MHZzX9aA1rKVMD1kRAiEAo2paHvU6ae6XqaymvVeplq9KmRY/gFyTSPfRtuTU8XcqvwIIaRABGgwyNzQ0MTI2MzI1NjAiDOKQzrGKT8YMVg2Q4yqcAotMa6Eh2mBLNWtIOSOlOrcS7htaf1hpPVuqnAxqCIZuozZSra7YXfR5WRSkBjjOVartUg4uaiUX2eVwOFZpzUf4fLAHiMAhbwsWBs4VfT/4B69zsWAuGme5EyWuVyfJWcwpjBIo14tJ/+HZgvJtVoaPPMJLuuBFpajyjSOrC5HeXVqEa7zwi2SRZ6QCZC2YaZ/yJi+A8CEtCXxLCausVfFtNgLUkZKd1qtOO7dQ+aF//2QGpx7jAsPBd0dmc+81E0xhPzl7i29pAVhkdoDpYV/N4mMw10H/1YTbCEu66/KtM4o+q16emLxouGwcEp5oBAWPvsNZ2dlVOVhupTslDliX9/r9HKVN3C7EPg6S+q3ImgO+0CRQYeW/pmeTMJa6pMEGOp0B1DHhriyOqloF6EvLRT8y+yvBOKVFI8p4FTjwO25E/vRMgq5lVHO9+k419UOwYcJ2O6/Yi50eiTxPtII3M3uxXMTj0xtnTapQCZ+YH99C9So9J437qTDuD/Teiw0j7ayQ0nsQrZqFbqoqhWWtu0AV+npA7Fce13mElBgjpPktxzM/5eCNi1MCvsrYjOhQ+nkEsRzFQ1nh+tKnIjUW5g==

# docker access variables
yourDockerUsername=simons36
yourDockerPassword=dckr_pat_tm0faZvK84dYdwwOpzaFmJETGKc

# exporting all variables to be used by next scripts
export AWS_ACCESS_KEY_ID=$aws_access_key_id
export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
export AWS_SESSION_TOKEN=$aws_session_token
export DockerUsername=$yourDockerUsername
export DockerPassword=$yourDockerPassword


