#!/bin/bash

# JAVA path
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export PATH=$JAVA_HOME/bin:$PATH

# aws access variables 
aws_access_key_id=ASIAT7ZCEPHYJALRPEEO
aws_secret_access_key=Q63nyVnmBLUgsMCyH7CjIXMaFHErV6gowLJN5yI/
aws_session_token=IQoJb3JpZ2luX2VjEMH//////////wEaCXVzLXdlc3QtMiJHMEUCIFQK21/RAPa+yiFivBBwHHOp6gLR+rn2HUdKRC4tbmtFAiEAvpIDAXL0wfuTSO3fJg+4vSsHXu0vE3GJIMjt9681GlIqvwIIehABGgwyNzQ0MTI2MzI1NjAiDD+gvOGUsAsUUP1GlyqcAn2+vUM4NARr37FAKy/A6fFTCzX43OUS3YQpndnOgCCxMxgUWhcxUIxC79dGNc79L5W+QLzWA+pV+8nNkwU3EyQyywhEzklG6q0K8GKZgeT4PFVXXr9EkG/PzSjRyQU/roVLZu3QjQ++ZzIizoz2fLdTZZfyjl5pZICIhOaXZhsRSJwgS/Zo/Cc21/wMWWY/Eez02veZf1jMjB46WDFyQ+SvrbDypKSp9lenP/t1wFOT+dcEell3IcnmYtRtkB9IarIGT4+QdvSs6UemfBcgwyN8Lr9//BVraIOVeo9kIJnJ1c0PqpZ+j2zNDQcZ8RyeG+uQ0RawngNNoGxhp0g7gOJW1mg+N0x59EKyotrI2b4Bft0GnXNfE1y0HB5MMLucqMEGOp0B3tJ1GuwGqFtbCpgsJP9+xYfxUmIa7hlJQuvFXzx8TWOA8n5OC/TGmX+9jb8l/A4amAhKrnJdhL+eITgcZvt8SRGUD3GYjs/fE6oqVQ5fL9uVzBwleQ7YTkpjfQV8Rao9DHmW7kL3blNhzYQ/vDAIeZHsXYeO81leLMEGDMhHCcZt/fdfuUNmuZoSVZWoy/bGE190mQseCE1Zb/J6PQ==
# docker access variables
yourDockerUsername=simons36
yourDockerPassword=dckr_pat_tm0faZvK84dYdwwOpzaFmJETGKc

# exporting all variables to be used by next scripts
export AWS_ACCESS_KEY_ID=$aws_access_key_id
export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
export AWS_SESSION_TOKEN=$aws_session_token
export DockerUsername=$yourDockerUsername
export DockerPassword=$yourDockerPassword


